### ISSUE TITLE
Document docker run add "-u root"

### ISSUE THREAD

**Issue by Fromeworld** [beautiful-atoms/beautiful-atoms#130]
Hi 
Today I tried "docker pull ghcr.io/beautiful-atoms/beautiful-atoms:latest" (latest =blender3.1) 
However, the document "Installation/Container image" section then suggests
```
docker run --rm \
       -v $(pwd):/workdir \
       ghcr.io/beautiful-atoms/beautiful-atoms:latest \
       blender -b -P render.py
```
and it gives the error "PermissionError: [Errno 13] Permission denied: '/tmp/beautiful_atoms.log'"

This can be resolved by adding "-u root" 
```
docker run -u root --rm \
       -v $(pwd):/workdir \
       ghcr.io/beautiful-atoms/beautiful-atoms:latest \
       blender -b -P render.py
```

**Comment by alchem0x2A** [comment]
Hi @Fromeworld 

Thanks for the testing! I think indeed this is a bug with permissions that the default user  `blender` (uid 1000) in the image does not have  write permission to paths like /tmp. Will fix this in the image.


On the other hand, while you definitely use the `-u root` switch as a temporary workaround, I do not recommend using the root user for general purpose documentation due to potential safety concerns.

**Comment by Fromeworld** [comment]
Great thanks! nice package~

**Comment by alchem0x2A** [comment]
@Fromeworld the bug with permission on `/tmp` has been fixed, however there are indeed some caveats when you're running the docker image on linux, in particular if the UID:GID pair on host does not match the preset user in container, when you're mounting volume. For example your normal user is UID 1001 on your linux host, but `blender` user in the image is 1000, you need to add a flag `-u 1001` to the docker run command, in order to have the correct mapping between host and docker.

**Comment by Fromeworld** [comment]
@alchem0x2A  hi, I just tested on my machine and the "/tmp" problem is solved. (maybe it's by luck, but I didn't add any UID)   thank you!
